# Generated by Django 4.2.1 on 2023-05-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('tag', models.CharField(max_length=100, verbose_name='тэг')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='OperatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='код мобильного оператора')),
            ],
            options={
                'db_table': 'operator_code',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата окончания рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('operator_code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notification.operatorcode')),
                ('tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notification.tag')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.BooleanField(verbose_name='Cтатус отправки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.client')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.order')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='operator_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.operatorcode'),
        ),
    ]
